### ISSUE TITLE
Could you add unixODBC?

### ISSUE THREAD

**Issue by ghost** [franko/lhelper-recipes#3]
https://www.unixodbc.org/download.html

**Comment by franko** [comment]
I have added a recipe for unixodbc, for the moment in a testing branch:

https://github.com/franko/lhelper-recipes/tree/testing-unixodbc

I have tested on linux and macos and seems fine but for the moment I cannot test on Windows but I may do that in a few days.

If you want to test yourself you may copy the recipe file from this branch in the directory "$prefix/share/lhelper/recipes" where "$prefix" is the base directory where you installed lhelper. You should also add the line:

unixodbc 2.3.11

in the file ""$prefix/share/lhelper/recipes/index".

Yet there is a problem with this package because it needs a few configuration files normally located in the /etc directory. When using the lhelper recipe they will be located in the "etc" directory but within the environment directory. A path to a lhelper specific folder will be hard-coded in one of the binary and this is not ok.

For the moment lhelper does not have an established solution for libraries or application that needs system-wide configuration files.

Normally the best options for these cases are:

- lookup in the system-wide /etc directory but do not install any stuff there
- locate the configuration files at run-time relatively to the application binary
   - in this way the application is self-contained and the configuration files can be edited from within the application's directory
   - to work it needs library support to locate the files at run-time and unixodbc may not have such a mechanism 
- locate the configuration files at run-time relatively to the user's directory

To figure out the better thing to do for the lhelper recipe would be to figure out a few use case of applications using unixodbc. What location for the configuration files would make more sense for an application using unixODBC ?

**Comment by ghost** [comment]
Yeah, a hard problem indeed. I think I will just compile and install unixODBC the normal way. MSYS2 has packages for unixODBC but Cygwin doesn't. After the launch of WSL/WSL2, Cygwin is almost dead with dozens of unmaintained packages, even GCC is still stuck at 11.3.0. I think I could use lhelper as a complement to Cygwin. I choose lhelper because it doesn't mess with the system wide packages of Cygwin. I don't know there is such a problem. Maybe it's time for me to abandon Cygwin. Thanks for your help anyway. Goodbye.

**Comment by franko** [comment]
I concur that packages requiring system-wide config files should be installed through the operating system.

MSYS2 is preferable for developers as it utilizes the Unix compatibility layer only as necessary and offers environments to build native Windows apps. MSYS2 is also more widely used than Cygwin.

No worries if the UnixODBC you requested isn't used. The exercise was still a valuable learning experience for me and I appreciate the feedback.
